# Generated by Django 4.1.6 on 2023-03-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_remove_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='userlikes',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
    ]
