# Generated by Django 4.1.6 on 2023-03-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_post_userlikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='userlikes',
            field=models.JSONField(default=None),
        ),
    ]
