# Generated by Django 4.1.6 on 2023-03-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0013_alter_post_userlikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='userlikes',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
